# 该文件由 CLI 自动生成，用于保存上一次确认后的配置。
LAST_CONFIG = {'project_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/tradingagents',
 'results_dir': './results',
 'data_cache_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/tradingagents/dataflows/data_cache',
 'local_data_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/agents/tradingagents_legacy/tradingagents/local_data',
 'data_tools_cache_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/agents/tradingagents_legacy/tradingagents/local_data/data_tools/cache',
 'data_tools_snapshot_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/agents/tradingagents_legacy/tradingagents/local_data/data_tools/snapshots',
 'market_data_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/agents/tradingagents_legacy/tradingagents/local_data/market_tools',
 'agent_output_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/agents/tradingagents_legacy/tradingagents/local_data/agents',
 'backtest_output_dir': '/cephfs/shared/yuanchengbo/simulator/TradingAgents/agents/tradingagents_legacy/tradingagents/local_data/backtests',
 'market_region': 'cn_a',
 'llm_provider': 'azure',
 'deep_think_llm': 'gpt-5.4',
 'quick_think_llm': 'gpt-5.4-mini',
 'backend_url': 'YOUR_AZURE_API_URL',
 'azure_api_version': '2024-12-01-preview',
 'content_filter_max_retries': 2,
 'content_filter_skip_message': 'Skipped due to Azure content policy filter.',
 'google_thinking_level': None,
 'openai_reasoning_effort': 'medium',
 'anthropic_effort': None,
 'internal_language': 'Chinese',
 'final_output_language': 'Chinese',
 'output_language': 'Chinese',
 'selected_analysts': ['market', 'social', 'news', 'fundamentals'],
 'research_depth': 1,
 'max_debate_rounds': 1,
 'max_risk_discuss_rounds': 1,
 'max_recur_limit': 100,
 'data_vendors': {'core_stock_apis': 'akshare',
                  'technical_indicators': 'akshare',
                  'fundamental_data': 'akshare',
                  'news_data': 'akshare'},
 'tool_vendors': {}}
